packaging_format = 2

id = "logseq"
name = "Logseq"
description.en = "Platform for knowledge management and collaboration"
description.fr = "Plate-forme de gestion des connaissances et de collaboration"

version = "0.9.10~ynh1"

maintainers = [""]

[upstream]
license = "AGPL-3.0"
website = "https://logseq.com/"
demo = "https://demo.logseq.com/"
admindoc = "https://docs.logseq.com/#/page/contents"
code = "https://github.com/logseq/logseq"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/logseq/logseq/archive/refs/tags/0.9.10.tar.gz"
        sha256 = "b01317901c891836f545f7def2489ef7962f0846b463be2226c863ff5558e50e"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = ""
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    #[resources.database]
    #type = "mysql"
